# Generated by Django 4.2.1 on 2023-06-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
