# Generated by Django 4.2.1 on 2023-06-20 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_payment_videos_studentcourse_paytoteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(null=True, upload_to='course_content/')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
