# Generated by Django 4.2.1 on 2023-06-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_content_delete_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytoteacher',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='paytoteacher',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='paytoteacher',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PayToTeacher',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
