# Generated by Django 4.2.1 on 2023-06-21 07:39

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_paytoteacher_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_content',
            name='content',
            field=models.FileField(null=True, upload_to=base.models.upload_location),
        ),
    ]
