# Generated by Django 4.2.1 on 2023-06-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_price',
            field=models.IntegerField(null=True),
        ),
    ]
