# Generated by Django 4.2.1 on 2023-06-23 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_payment_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.teacher'),
        ),
    ]
